class Food {
  final String name;
  final String category;
  final double price;
  final double rating;
  final String description;
  final List<String> ingredients;
  final String imageUrl;
  final String restaurantName;
  final String deliveryTime;

  Food({
    required this.name,
    required this.category,
    required this.price,
    required this.rating,
    required this.description,
    required this.ingredients,
    required this.imageUrl,
    this.restaurantName = 'QuickBite Kitchen',
    this.deliveryTime = '25-30 min',
  });
}

List<Food> foodList = [
  // ---------- PIZZA ----------
  Food(
    name: 'Margherita Pizza',
    category: 'Pizza',
    price: 199,
    rating: 4.5,
    description: 'Classic pizza topped with fresh mozzarella, tomato sauce and basil.',
    ingredients: ['Mozzarella cheese', 'Tomato sauce', 'Fresh basil', 'Pizza dough', 'Olive oil'],
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
  ),
  Food(
    name: 'Veg Pizza',
    category: 'Pizza',
    price: 179,
    rating: 4.1,
    description: 'Loaded with fresh vegetables and mozzarella cheese.',
    ingredients: ['Mozzarella cheese', 'Bell peppers', 'Onions', 'Sweet corn', 'Olives', 'Pizza dough'],
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
  ),
  Food(
    name: 'Pepperoni Pizza',
    category: 'Pizza',
    price: 249,
    rating: 4.6,
    description: 'Loaded with spicy pepperoni slices and extra cheese.',
    ingredients: ['Pepperoni', 'Mozzarella cheese', 'Tomato sauce', 'Pizza dough', 'Oregano'],
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
  ),
  Food(
    name: 'Farmhouse Pizza',
    category: 'Pizza',
    price: 229,
    rating: 4.3,
    description: 'A garden-fresh pizza loaded with capsicum, onion, tomato and corn.',
    ingredients: ['Capsicum', 'Onion', 'Tomato', 'Sweet corn', 'Mozzarella cheese', 'Pizza dough'],
    imageUrl: 'https://images.unsplash.com/photo-1601924928357-9c5e9b0e4f5b?w=400',
  ),
  Food(
    name: 'Paneer Tikka Pizza',
    category: 'Pizza',
    price: 259,
    rating: 4.4,
    description: 'Indian-style pizza topped with marinated paneer tikka chunks.',
    ingredients: ['Paneer', 'Tikka masala', 'Onion', 'Capsicum', 'Mozzarella cheese', 'Pizza dough'],
    imageUrl: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400',
  ),
  Food(
    name: 'BBQ Chicken Pizza',
    category: 'Pizza',
    price: 279,
    rating: 4.5,
    description: 'Smoky BBQ chicken with onions and a tangy barbecue base.',
    ingredients: ['Chicken', 'BBQ sauce', 'Onion', 'Mozzarella cheese', 'Pizza dough'],
    imageUrl: 'https://images.unsplash.com/photo-1593504049359-74330189a345?w=400',
  ),
  Food(
    name: 'Four Cheese Pizza',
    category: 'Pizza',
    price: 269,
    rating: 4.7,
    description: 'A rich blend of mozzarella, cheddar, parmesan and feta cheese.',
    ingredients: ['Mozzarella', 'Cheddar', 'Parmesan', 'Feta', 'Pizza dough'],
    imageUrl: 'https://images.unsplash.com/photo-1548365328-9f547fb0953b?w=400',
  ),

  // ---------- BURGER ----------
  Food(
    name: 'Cheese Burger',
    category: 'Burger',
    price: 129,
    rating: 4.3,
    description: 'Juicy grilled patty with cheese, lettuce and our special sauce.',
    ingredients: ['Beef patty', 'Cheddar cheese', 'Lettuce', 'Tomato', 'Burger bun', 'Special sauce'],
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
  ),
  Food(
    name: 'Veg Burger',
    category: 'Burger',
    price: 99,
    rating: 4.0,
    description: 'A crispy vegetable patty with fresh lettuce and mayo.',
    ingredients: ['Veg patty', 'Lettuce', 'Tomato', 'Mayo', 'Burger bun'],
    imageUrl: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400',
  ),
  Food(
    name: 'Double Patty Burger',
    category: 'Burger',
    price: 179,
    rating: 4.6,
    description: 'Two juicy beef patties stacked with cheese and pickles.',
    ingredients: ['Beef patty x2', 'Cheddar cheese', 'Pickles', 'Onion', 'Burger bun'],
    imageUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400',
  ),
  Food(
    name: 'Chicken Burger',
    category: 'Burger',
    price: 149,
    rating: 4.4,
    description: 'Crispy fried chicken fillet with lettuce and mayo.',
    ingredients: ['Chicken fillet', 'Lettuce', 'Mayo', 'Burger bun'],
    imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400',
  ),
  Food(
    name: 'Spicy Paneer Burger',
    category: 'Burger',
    price: 139,
    rating: 4.2,
    description: 'Spicy paneer patty with tangy sauce and fresh veggies.',
    ingredients: ['Paneer patty', 'Spicy sauce', 'Lettuce', 'Onion', 'Burger bun'],
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400',
  ),
  Food(
    name: 'Bacon Burger',
    category: 'Burger',
    price: 189,
    rating: 4.5,
    description: 'Crispy bacon strips layered with a juicy beef patty.',
    ingredients: ['Beef patty', 'Bacon', 'Cheddar cheese', 'Burger bun'],
    imageUrl: 'https://images.unsplash.com/photo-1561758033-7e924f619b47?w=400',
  ),
  Food(
    name: 'Mushroom Swiss Burger',
    category: 'Burger',
    price: 169,
    rating: 4.3,
    description: 'Sauteed mushrooms with melted swiss cheese on a beef patty.',
    ingredients: ['Beef patty', 'Mushrooms', 'Swiss cheese', 'Burger bun'],
    imageUrl: 'https://images.unsplash.com/photo-1550317138-10000687a72b?w=400',
  ),

  // ---------- BIRYANI ----------
  Food(
    name: 'Chicken Biryani',
    category: 'Biryani',
    price: 249,
    rating: 4.7,
    description: 'Fragrant basmati rice cooked with spiced chicken and herbs.',
    ingredients: ['Basmati rice', 'Chicken', 'Biryani masala', 'Onions', 'Yogurt', 'Mint leaves'],
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
  ),
  Food(
    name: 'Mutton Biryani',
    category: 'Biryani',
    price: 299,
    rating: 4.8,
    description: 'Slow-cooked mutton with aromatic basmati rice and spices.',
    ingredients: ['Basmati rice', 'Mutton', 'Biryani masala', 'Onions', 'Yogurt', 'Saffron'],
    imageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=400',
  ),
  Food(
    name: 'Veg Biryani',
    category: 'Biryani',
    price: 179,
    rating: 4.2,
    description: 'A flavorful rice dish loaded with mixed vegetables and spices.',
    ingredients: ['Basmati rice', 'Mixed vegetables', 'Biryani masala', 'Onions', 'Mint leaves'],
    imageUrl: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=400',
  ),
  Food(
    name: 'Egg Biryani',
    category: 'Biryani',
    price: 199,
    rating: 4.3,
    description: 'Spiced basmati rice topped with boiled eggs and fried onions.',
    ingredients: ['Basmati rice', 'Boiled eggs', 'Biryani masala', 'Fried onions'],
    imageUrl: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=400',
  ),
  Food(
    name: 'Prawn Biryani',
    category: 'Biryani',
    price: 319,
    rating: 4.6,
    description: 'Juicy prawns cooked with fragrant rice and coastal spices.',
    ingredients: ['Basmati rice', 'Prawns', 'Biryani masala', 'Coconut', 'Curry leaves'],
    imageUrl: 'https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=400',
  ),
  Food(
    name: 'Hyderabadi Dum Biryani',
    category: 'Biryani',
    price: 279,
    rating: 4.7,
    description: 'Authentic dum-cooked biryani sealed with dough for rich flavor.',
    ingredients: ['Basmati rice', 'Chicken', 'Dum masala', 'Saffron', 'Ghee'],
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400',
  ),
  Food(
    name: 'Paneer Biryani',
    category: 'Biryani',
    price: 209,
    rating: 4.1,
    description: 'Soft paneer cubes tossed in fragrant spiced rice.',
    ingredients: ['Basmati rice', 'Paneer', 'Biryani masala', 'Onions', 'Mint leaves'],
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400',
  ),

  // ---------- DRINKS ----------
  Food(
    name: 'Cold Coffee',
    category: 'Drinks',
    price: 89,
    rating: 4.2,
    description: 'Chilled coffee blended with milk and ice cream.',
    ingredients: ['Coffee', 'Milk', 'Ice cream', 'Sugar', 'Ice cubes'],
    imageUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400',
  ),
  Food(
    name: 'Mango Smoothie',
    category: 'Drinks',
    price: 99,
    rating: 4.5,
    description: 'A creamy, refreshing smoothie made with fresh mango pulp.',
    ingredients: ['Mango', 'Yogurt', 'Milk', 'Sugar'],
    imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
  ),
  Food(
    name: 'Fresh Lime Soda',
    category: 'Drinks',
    price: 59,
    rating: 4.0,
    description: 'A zesty, fizzy drink made with fresh lime juice.',
    ingredients: ['Lime juice', 'Soda water', 'Sugar', 'Mint leaves'],
    imageUrl: 'https://images.unsplash.com/photo-1437418747212-8d9709afab22?w=400',
  ),
  Food(
    name: 'Chocolate Milkshake',
    category: 'Drinks',
    price: 109,
    rating: 4.6,
    description: 'Rich and creamy milkshake blended with chocolate syrup.',
    ingredients: ['Milk', 'Chocolate syrup', 'Ice cream', 'Sugar'],
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400',
  ),
  Food(
    name: 'Watermelon Juice',
    category: 'Drinks',
    price: 79,
    rating: 4.1,
    description: 'A naturally sweet and hydrating fresh watermelon juice.',
    ingredients: ['Watermelon', 'Mint leaves', 'Ice cubes'],
    imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
  ),
  Food(
    name: 'Masala Chai',
    category: 'Drinks',
    price: 39,
    rating: 4.4,
    description: 'Traditional Indian spiced tea brewed with milk.',
    ingredients: ['Tea leaves', 'Milk', 'Cardamom', 'Ginger', 'Sugar'],
    imageUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400',
  ),
  Food(
    name: 'Iced Lemon Tea',
    category: 'Drinks',
    price: 69,
    rating: 4.0,
    description: 'A refreshing chilled tea with a citrusy lemon twist.',
    ingredients: ['Tea', 'Lemon', 'Sugar', 'Ice cubes'],
    imageUrl: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?w=400',
  ),

  // ---------- DESSERTS ----------
  Food(
    name: 'Chocolate Brownie',
    category: 'Desserts',
    price: 99,
    rating: 4.6,
    description: 'Rich, fudgy chocolate brownie served warm.',
    ingredients: ['Dark chocolate', 'Butter', 'Eggs', 'Flour', 'Sugar', 'Walnuts'],
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400',
  ),
  Food(
    name: 'Gulab Jamun',
    category: 'Desserts',
    price: 79,
    rating: 4.5,
    description: 'Soft milk dumplings soaked in fragrant sugar syrup.',
    ingredients: ['Milk powder', 'Sugar syrup', 'Cardamom', 'Ghee'],
    imageUrl: 'https://images.unsplash.com/photo-1606471191009-63994c53433b?w=400',
  ),
  Food(
    name: 'Vanilla Ice Cream',
    category: 'Desserts',
    price: 69,
    rating: 4.3,
    description: 'Classic creamy vanilla ice cream scoop.',
    ingredients: ['Milk', 'Cream', 'Vanilla', 'Sugar'],
    imageUrl: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68a?w=400',
  ),
  Food(
    name: 'Cheesecake',
    category: 'Desserts',
    price: 149,
    rating: 4.7,
    description: 'Creamy baked cheesecake with a buttery biscuit base.',
    ingredients: ['Cream cheese', 'Biscuit base', 'Sugar', 'Eggs'],
    imageUrl: 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=400',
  ),
  Food(
    name: 'Rasmalai',
    category: 'Desserts',
    price: 89,
    rating: 4.6,
    description: 'Soft cottage cheese patties soaked in sweetened, flavored milk.',
    ingredients: ['Cottage cheese', 'Milk', 'Sugar', 'Cardamom', 'Pistachios'],
    imageUrl: 'https://images.unsplash.com/photo-1631206753348-db44968fd440?w=400',
  ),
  Food(
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    price: 129,
    rating: 4.8,
    description: 'Warm chocolate cake with a molten chocolate center.',
    ingredients: ['Dark chocolate', 'Butter', 'Eggs', 'Flour', 'Sugar'],
    imageUrl: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400',
  ),
  Food(
    name: 'Fruit Custard',
    category: 'Desserts',
    price: 75,
    rating: 4.1,
    description: 'Chilled custard mixed with fresh seasonal fruits.',
    ingredients: ['Milk', 'Custard powder', 'Mixed fruits', 'Sugar'],
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
  ),

  // ---------- FAST FOOD ----------
  Food(
    name: 'French Fries',
    category: 'Fast Food',
    price: 89,
    rating: 4.2,
    description: 'Crispy golden fries seasoned with salt and herbs.',
    ingredients: ['Potatoes', 'Salt', 'Herbs', 'Oil'],
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
  ),
  Food(
    name: 'Chicken Nuggets',
    category: 'Fast Food',
    price: 119,
    rating: 4.3,
    description: 'Crispy fried chicken nuggets served with dipping sauce.',
    ingredients: ['Chicken', 'Breadcrumbs', 'Spices', 'Oil'],
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400',
  ),
  Food(
    name: 'Spring Rolls',
    category: 'Fast Food',
    price: 99,
    rating: 4.0,
    description: 'Crispy rolls stuffed with vegetables and glass noodles.',
    ingredients: ['Cabbage', 'Carrots', 'Glass noodles', 'Spring roll sheets'],
    imageUrl: 'https://images.unsplash.com/photo-1548811256-1627d99c5a5d?w=400',
  ),
  Food(
    name: 'Onion Rings',
    category: 'Fast Food',
    price: 79,
    rating: 4.1,
    description: 'Crispy battered onion rings, fried golden brown.',
    ingredients: ['Onions', 'Batter', 'Breadcrumbs', 'Oil'],
    imageUrl: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400',
  ),
  Food(
    name: 'Cheese Garlic Bread',
    category: 'Fast Food',
    price: 109,
    rating: 4.4,
    description: 'Toasted bread loaded with garlic butter and melted cheese.',
    ingredients: ['Bread', 'Garlic butter', 'Mozzarella cheese'],
    imageUrl: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=400',
  ),
  Food(
    name: 'Nachos with Cheese',
    category: 'Fast Food',
    price: 129,
    rating: 4.3,
    description: 'Crunchy nachos topped with melted cheese and salsa.',
    ingredients: ['Corn chips', 'Cheese sauce', 'Salsa', 'Jalapenos'],
    imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=400',
  ),

  // ---------- SOUTH INDIAN ----------
  Food(
    name: 'Masala Dosa',
    category: 'South Indian',
    price: 89,
    rating: 4.5,
    description: 'Crispy rice crepe filled with spiced potato filling.',
    ingredients: ['Rice batter', 'Potato filling', 'Sambar', 'Coconut chutney'],
    imageUrl: 'https://images.unsplash.com/photo-1630383249896-44627c651da9?w=400',
  ),
  Food(
    name: 'Idli Sambar',
    category: 'South Indian',
    price: 69,
    rating: 4.4,
    description: 'Soft steamed rice cakes served with sambar and chutney.',
    ingredients: ['Idli batter', 'Sambar', 'Coconut chutney'],
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
  ),
  Food(
    name: 'Medu Vada',
    category: 'South Indian',
    price: 59,
    rating: 4.2,
    description: 'Crispy fried lentil donuts served with chutney and sambar.',
    ingredients: ['Urad dal', 'Spices', 'Sambar', 'Coconut chutney'],
    imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
  ),
  Food(
    name: 'Pongal',
    category: 'South Indian',
    price: 79,
    rating: 4.1,
    description: 'A comforting rice and lentil porridge tempered with spices.',
    ingredients: ['Rice', 'Moong dal', 'Pepper', 'Cumin', 'Ghee'],
    imageUrl: 'https://images.unsplash.com/photo-1589301773859-d57c1f51e273?w=400',
  ),
  Food(
    name: 'Uttapam',
    category: 'South Indian',
    price: 89,
    rating: 4.3,
    description: 'A thick savory pancake topped with onions and chillies.',
    ingredients: ['Rice batter', 'Onions', 'Green chillies', 'Coriander'],
    imageUrl: 'https://images.unsplash.com/photo-1630383249896-44627c651da9?w=400',
  ),

  // ---------- CHINESE ----------
  Food(
    name: 'Veg Hakka Noodles',
    category: 'Chinese',
    price: 139,
    rating: 4.3,
    description: 'Stir-fried noodles tossed with fresh vegetables and soy sauce.',
    ingredients: ['Noodles', 'Mixed vegetables', 'Soy sauce', 'Garlic'],
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400',
  ),
  Food(
    name: 'Chicken Manchurian',
    category: 'Chinese',
    price: 189,
    rating: 4.5,
    description: 'Crispy chicken tossed in a tangy, spicy Manchurian sauce.',
    ingredients: ['Chicken', 'Manchurian sauce', 'Garlic', 'Spring onions'],
    imageUrl: 'https://images.unsplash.com/photo-1626776877144-71d2dd6a4e2c?w=400',
  ),
  Food(
    name: 'Veg Fried Rice',
    category: 'Chinese',
    price: 129,
    rating: 4.2,
    description: 'Wok-tossed rice with fresh vegetables and soy sauce.',
    ingredients: ['Rice', 'Mixed vegetables', 'Soy sauce', 'Spring onions'],
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
  ),
  Food(
    name: 'Chilli Paneer',
    category: 'Chinese',
    price: 169,
    rating: 4.4,
    description: 'Crispy paneer cubes tossed in a spicy chilli sauce.',
    ingredients: ['Paneer', 'Capsicum', 'Chilli sauce', 'Garlic'],
    imageUrl: 'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=400',
  ),
  Food(
    name: 'Spring Onion Momos',
    category: 'Chinese',
    price: 119,
    rating: 4.3,
    description: 'Steamed dumplings filled with veggies and spring onion.',
    ingredients: ['Flour wrapper', 'Cabbage', 'Spring onion', 'Carrots'],
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=400',
  ),
];

List<String> categoryList = [
  'Pizza',
  'Burger',
  'Biryani',
  'Drinks',
  'Desserts',
  'Fast Food',
  'South Indian',
  'Chinese',
];